/** Default website sell/buy category catalog (admin can toggle + set images). */
export const WEBSITE_CATEGORY_DEFS = [
  {
    key: 'mobile',
    label: 'Mobile',
    sellPath: '/sell-old-mobile-phones/brand',
    buyPath: '/buy/mobile/brand',
    enabledSell: true,
    enabledBuy: true,
    imageUrl: '',
    sortOrder: 1,
  },
  {
    key: 'tablet',
    label: 'Tablet',
    sellPath: '/sell-tablet/brand',
    buyPath: '/buy/tablet/brand',
    enabledSell: true,
    enabledBuy: true,
    imageUrl: '',
    sortOrder: 2,
  },
  {
    key: 'laptop',
    label: 'Laptop',
    sellPath: '/sell-old-laptops/brand',
    buyPath: '/buy/laptop/brand',
    enabledSell: true,
    enabledBuy: true,
    imageUrl: '',
    sortOrder: 3,
  },
  {
    key: 'mac',
    label: 'Mac',
    sellPath: '/sell-imac/brand',
    buyPath: '/buy/mac/brand',
    enabledSell: true,
    enabledBuy: true,
    imageUrl: '',
    sortOrder: 4,
  },
  {
    key: 'tv',
    label: 'TV',
    sellPath: '/sell/tv/brand',
    buyPath: '/buy/tv/brand',
    enabledSell: true,
    enabledBuy: true,
    imageUrl: '',
    sortOrder: 5,
  },
  {
    key: 'earbuds',
    label: 'Earbuds',
    sellPath: '/sell/earbuds/brand',
    buyPath: '/buy/earbuds/brand',
    enabledSell: true,
    enabledBuy: true,
    imageUrl: '',
    sortOrder: 6,
  },
  {
    key: 'refrigerator',
    label: 'Refrigerator',
    sellPath: '/sell/refrigerator/brand',
    buyPath: '/buy/refrigerator/brand',
    enabledSell: true,
    enabledBuy: true,
    imageUrl: '',
    sortOrder: 7,
  },
  {
    key: 'smartwatch',
    label: 'Smartwatch',
    sellPath: '/sell/smartwatch/brand',
    buyPath: '/buy/smartwatch/brand',
    enabledSell: false,
    enabledBuy: true,
    imageUrl: '',
    sortOrder: 8,
  },
];

export function defaultWebsiteCategories() {
  return WEBSITE_CATEGORY_DEFS.map((c) => ({ ...c }));
}
